# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grpc_event.proto\"\x1d\n\x0c\x45ventRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\'\n\rEventResponse\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Event\"q\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\t2:\n\x0c\x45ventService\x12*\n\tGetEvents\x12\r.EventRequest\x1a\x0e.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EVENTREQUEST']._serialized_start=20
  _globals['_EVENTREQUEST']._serialized_end=49
  _globals['_EVENTRESPONSE']._serialized_start=51
  _globals['_EVENTRESPONSE']._serialized_end=90
  _globals['_EVENT']._serialized_start=92
  _globals['_EVENT']._serialized_end=205
  _globals['_EVENTSERVICE']._serialized_start=207
  _globals['_EVENTSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
