services:
  - type: web
    name: event-scout
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # This runs your Flask app using Gunicorn (WSGI)
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SERP_API_KEY
        sync: false
    postBuildCommand: "python -m unittest -v tests/test_browse.py"
